# Generated by Django 5.0.6 on 2024-06-21 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0003_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('quantidade_habitantes', models.DecimalField(decimal_places=3, max_digits=3)),
                ('clima', models.CharField(max_length=40, unique=True)),
                ('data_fundacao', models.CharField(max_length=40, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interno.estado')),
            ],
        ),
    ]
